"""Pure-JAX forward fixed-point and backward score training."""

from cg_bms_jax.training.backward import (
    BackwardStepMetrics,
    BackwardTrainingConfig,
    BackwardTrainingResult,
    collect_backward_pairs,
    make_backward_update_step,
    train_backward_score,
)
from cg_bms_jax.training.bridge_pretrain import (
    BridgeCheckpointCallback,
    BridgePretrainConfig,
    BridgePretrainResult,
    BridgePretrainStepMetrics,
    EndpointBatchProvider,
    make_array_endpoint_provider,
    make_bridge_pretrain_update_step,
    remaining_bridge_variance,
    train_bridge_pretrain,
    variance_weighted_bridge_loss,
)
from cg_bms_jax.training.forward import (
    ForwardOuterCallback,
    ForwardOuterSnapshot,
    ForwardStepMetrics,
    ForwardTrainingConfig,
    ForwardTrainingResult,
    clip_target_score_by_bead,
    collect_forward_pairs,
    make_forward_update_step,
    train_forward_fixed_point,
)
from cg_bms_jax.training.state import (
    ControlApply,
    ControllerTrainState,
    flax_apply,
    initialize_train_state,
    make_learning_rate,
    make_optimizer,
    split_flax_variables,
)

__all__ = [
    "BackwardStepMetrics",
    "BackwardTrainingConfig",
    "BackwardTrainingResult",
    "BridgePretrainConfig",
    "BridgeCheckpointCallback",
    "BridgePretrainResult",
    "BridgePretrainStepMetrics",
    "ControlApply",
    "ControllerTrainState",
    "EndpointBatchProvider",
    "ForwardStepMetrics",
    "ForwardOuterCallback",
    "ForwardOuterSnapshot",
    "ForwardTrainingConfig",
    "ForwardTrainingResult",
    "clip_target_score_by_bead",
    "collect_backward_pairs",
    "collect_forward_pairs",
    "flax_apply",
    "initialize_train_state",
    "make_backward_update_step",
    "make_array_endpoint_provider",
    "make_bridge_pretrain_update_step",
    "make_forward_update_step",
    "make_learning_rate",
    "make_optimizer",
    "remaining_bridge_variance",
    "split_flax_variables",
    "train_backward_score",
    "train_bridge_pretrain",
    "train_forward_fixed_point",
    "variance_weighted_bridge_loss",
]
