"""CG-BG-compatible archive construction with provenance validation."""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import numpy as np

from .weights import WeightResult


def _scalar_string(value: Any) -> str:
    array = np.asarray(value)
    if array.size != 1:
        raise ValueError("Expected one scalar string")
    item = array.reshape(()).item()
    if isinstance(item, bytes):
        return item.decode("utf-8")
    return str(item)


def build_reweight_payload(
    *,
    physical_coordinates: Any,
    energy: Any,
    logq_ambient: Any,
    result: WeightResult,
    metadata: Mapping[str, Any],
    standardized_ambient: Any | None = None,
    support_mask: Any | None = None,
    extra: Mapping[str, Any] | None = None,
) -> dict[str, np.ndarray]:
    """Build an extended archive while retaining CG-BG's ``R/logp/U/logw``."""

    payload: dict[str, np.ndarray] = {
        "R": np.asarray(physical_coordinates),
        "U": np.asarray(energy),
        "logp": np.asarray(result.proposal_log_density),
        "logw": np.asarray(result.logw),
        "logw_raw": np.asarray(result.logw_raw),
        "weights": np.asarray(result.weights),
        "logq_ambient": np.asarray(logq_ambient),
        "valid_mask": np.asarray(result.valid_mask, dtype=bool),
        "support_mask": np.asarray(result.valid_mask if support_mask is None else support_mask, dtype=bool),
        "sampler_kind": np.asarray("pf_ode"),
        "density_mode": np.asarray(result.density_mode),
        "metadata_json": np.asarray(json.dumps(dict(metadata), sort_keys=True, separators=(",", ":"))),
    }
    if standardized_ambient is not None:
        payload["X_standardized"] = np.asarray(standardized_ambient)
    if extra:
        reserved = set(payload)
        overlap = reserved.intersection(extra)
        if overlap:
            raise KeyError(f"Extra payload attempts to replace reserved fields: {sorted(overlap)}")
        payload.update({key: np.asarray(value) for key, value in extra.items()})
    validate_reweight_payload(payload, expected_density_mode=result.density_mode)
    return payload


def validate_reweight_payload(
    payload: Mapping[str, Any],
    *,
    expected_density_mode: str | None = None,
    expected_metadata: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    required = {
        "R",
        "U",
        "logp",
        "logw",
        "logw_raw",
        "weights",
        "logq_ambient",
        "valid_mask",
        "support_mask",
        "sampler_kind",
        "density_mode",
        "metadata_json",
    }
    missing = required.difference(payload)
    if missing:
        raise KeyError(f"Reweight archive is missing fields: {sorted(missing)}")
    if _scalar_string(payload["sampler_kind"]) != "pf_ode":
        raise ValueError("Only samples generated by the PF-ODE may carry proposal log densities")
    mode = _scalar_string(payload["density_mode"])
    if mode not in {"ambient_exact", "cgbg_compat"}:
        raise ValueError(f"Unknown density mode {mode!r}")
    if expected_density_mode is not None and mode != expected_density_mode:
        raise ValueError(f"Expected density mode {expected_density_mode!r}, found {mode!r}")

    energy = np.asarray(payload["U"])
    sample_shape = energy.shape
    for field in ("logp", "logw", "logw_raw", "weights", "logq_ambient", "valid_mask", "support_mask"):
        if np.asarray(payload[field]).shape != sample_shape:
            raise ValueError(f"Field {field!r} does not match energy sample shape {sample_shape}")
    coordinates = np.asarray(payload["R"])
    if coordinates.shape[: len(sample_shape)] != sample_shape:
        raise ValueError("Coordinate leading dimensions do not match U/logq")
    weights = np.asarray(payload["weights"], dtype=float)
    valid = np.asarray(payload["valid_mask"], dtype=bool)
    support = np.asarray(payload["support_mask"], dtype=bool)
    if np.any(weights < 0) or np.any(~np.isfinite(weights)):
        raise ValueError("Weights must be finite and non-negative")
    if np.any(weights[~valid] != 0):
        raise ValueError("Invalid samples must have exactly zero weight")
    if np.any(weights[~support] != 0):
        raise ValueError("Out-of-domain samples must have exactly zero weight")
    if not valid.any():
        raise ValueError("Reweight archive has no valid finite-weight samples")
    if not np.isclose(weights.sum(), 1.0, rtol=1e-6, atol=1e-8):
        raise ValueError(f"Weights do not sum to one: {weights.sum()}")
    metadata = json.loads(_scalar_string(payload["metadata_json"]))
    if not isinstance(metadata, dict):
        raise ValueError("metadata_json must decode to an object")
    domain = metadata.get("domain")
    if not isinstance(domain, dict):
        raise ValueError("metadata_json must record the relative-coordinate domain")
    missing_domain = {"box", "anchor", "margin", "support_mode"}.difference(domain)
    if missing_domain:
        raise ValueError(f"Domain metadata is missing {sorted(missing_domain)}")
    if expected_metadata:
        for key, expected in expected_metadata.items():
            if metadata.get(key) != expected:
                raise ValueError(f"Metadata mismatch for {key!r}: {metadata.get(key)!r} != {expected!r}")

    if metadata.get("target_mode") == "pmf_canonical_support":
        implementation_abi = metadata.get(
            "target_implementation_abi",
            # Archives written before the ABI was included in identity
            # metadata used the topology-gated v2 decomposition.
            "ala2_canonical_support_v2",
        )
        common_components = {
            "U_pmf",
            "U_pmf_raw",
            "U_pmf_effective",
            "U_pmf_floor_delta",
            "U_pmf_transform_delta",
            "U_bond",
            "U_angle",
            "U_repulsion",
            "U_support",
            "U_cb",
            "U_target",
        }
        if implementation_abi == "ala2_canonical_additive_v3":
            required_components = common_components | {"U_pmf_scaled"}
        elif implementation_abi == "ala2_canonical_support_v2":
            required_components = common_components | {
                "pmf_topology_gate",
                "U_pmf_gated",
            }
        else:
            raise ValueError(
                "Unknown pmf_canonical_support target implementation ABI "
                f"{implementation_abi!r}"
            )
        missing_components = required_components.difference(payload)
        if missing_components:
            raise KeyError(
                "Canonical-target archive is missing energy components: "
                f"{sorted(missing_components)}"
            )
        for field in required_components:
            if np.asarray(payload[field]).shape != sample_shape:
                raise ValueError(
                    f"Canonical energy component {field!r} does not match {sample_shape}"
                )
        if not all(
            metadata.get(field)
            for field in (
                "formal_target_signature",
                "training_target_signature",
                "topology_signature",
            )
        ):
            raise ValueError("Canonical-target metadata is missing immutable target signatures")

        valid_component = valid & support

        def require_close(left: Any, right: Any, label: str) -> None:
            lhs = np.asarray(left, dtype=np.float64)[valid_component]
            rhs = np.asarray(right, dtype=np.float64)[valid_component]
            if np.any(~np.isfinite(lhs)) or np.any(~np.isfinite(rhs)):
                raise ValueError(f"{label} is non-finite on valid support")
            if not np.allclose(lhs, rhs, rtol=2.0e-5, atol=2.0e-4):
                raise ValueError(f"Canonical target decomposition mismatch: {label}")

        require_close(payload["U"], payload["U_target"], "U == U_target")
        require_close(payload["U_pmf"], payload["U_pmf_raw"], "U_pmf == U_pmf_raw")
        require_close(
            np.asarray(payload["U_pmf_effective"]) - np.asarray(payload["U_pmf_raw"]),
            payload["U_pmf_transform_delta"],
            "PMF energy-window delta",
        )
        require_close(
            payload["U_pmf_floor_delta"],
            payload["U_pmf_transform_delta"],
            "legacy PMF transform-delta alias",
        )
        require_close(
            np.asarray(payload["U_bond"])
            + np.asarray(payload["U_angle"])
            + np.asarray(payload["U_repulsion"]),
            payload["U_support"],
            "U_support component sum",
        )
        if implementation_abi == "ala2_canonical_additive_v3":
            if "pmf_scale" not in metadata:
                raise ValueError("Additive-v3 metadata is missing pmf_scale")
            pmf_scale_array = np.asarray(metadata["pmf_scale"], dtype=np.float64)
            if pmf_scale_array.size != 1 or not np.isfinite(
                pmf_scale_array.reshape(()).item()
            ):
                raise ValueError(
                    "Additive-v3 pmf_scale must be one finite non-negative scalar"
                )
            pmf_scale = float(pmf_scale_array.reshape(()).item())
            if pmf_scale < 0.0:
                raise ValueError(
                    "Additive-v3 pmf_scale must be one finite non-negative scalar"
                )
            require_close(
                pmf_scale * np.asarray(payload["U_pmf_effective"]),
                payload["U_pmf_scaled"],
                "U_pmf_scaled == pmf_scale * U_pmf_effective",
            )
            require_close(
                np.asarray(payload["U_pmf_scaled"])
                + np.asarray(payload["U_support"])
                + np.asarray(payload["U_cb"]),
                payload["U_target"],
                "formal U_target component sum",
            )
        else:
            gate = np.asarray(payload["pmf_topology_gate"], dtype=np.float64)
            if np.any(~np.isfinite(gate[valid_component])) or np.any(
                (gate[valid_component] < 0.0) | (gate[valid_component] > 1.0)
            ):
                raise ValueError("pmf_topology_gate must be finite and lie in [0,1]")
            require_close(
                np.asarray(payload["U_pmf_gated"])
                + np.asarray(payload["U_support"])
                + np.asarray(payload["U_cb"]),
                payload["U_target"],
                "formal U_target component sum",
            )
    if metadata.get("target_mode") == "openmm_bms_chirality":
        required_components = {
            "U_openmm",
            "U_improper",
            "U_target",
            "U_com_reduced",
            "target_reduced_energy",
        }
        missing_components = required_components.difference(payload)
        if missing_components:
            raise KeyError(
                "All-atom target archive is missing energy components: "
                f"{sorted(missing_components)}"
            )
        for field in required_components:
            if np.asarray(payload[field]).shape != sample_shape:
                raise ValueError(
                    f"All-atom energy component {field!r} does not match "
                    f"{sample_shape}"
                )
        if metadata.get("state_density_mode") != "ambient_66d_aux_com_exact":
            raise ValueError(
                "All-atom reweighting requires ambient_66d_aux_com_exact"
            )
        if metadata.get("density_mode") != "ambient_exact":
            raise ValueError(
                "All-atom formal weights require exact ambient log density"
            )
        if coordinates.shape != (*sample_shape, 22, 3):
            raise ValueError(
                "All-atom reweighting requires R with trailing shape (22,3)"
            )
        if "X_standardized" not in payload or np.asarray(
            payload["X_standardized"]
        ).shape != coordinates.shape:
            raise ValueError(
                "All-atom reweighting requires X_standardized matching R"
            )
        if not all(
            metadata.get(field)
            for field in (
                "formal_target_signature",
                "training_target_signature",
                "topology_signature",
                "atom_order_signature",
            )
        ):
            raise ValueError(
                "All-atom metadata is missing immutable target/order signatures"
            )
        valid_component = valid & support

        def require_aa_close(left: Any, right: Any, label: str) -> None:
            lhs = np.asarray(left, dtype=np.float64)[valid_component]
            rhs = np.asarray(right, dtype=np.float64)[valid_component]
            if np.any(~np.isfinite(lhs)) or np.any(~np.isfinite(rhs)):
                raise ValueError(f"{label} is non-finite on valid support")
            if not np.allclose(lhs, rhs, rtol=2.0e-5, atol=2.0e-4):
                raise ValueError(
                    f"All-atom target decomposition mismatch: {label}"
                )

        require_aa_close(payload["U"], payload["U_target"], "U == U_target")
        require_aa_close(
            np.asarray(payload["U_openmm"])
            + np.asarray(payload["U_improper"]),
            payload["U_target"],
            "U_target == U_openmm + U_improper",
        )
        kT = metadata.get("kT_kj_mol")
        if kT is None or not np.isfinite(float(kT)) or float(kT) <= 0.0:
            raise ValueError(
                "All-atom metadata must record one positive kT_kj_mol"
            )
        require_aa_close(
            np.asarray(payload["U_target"]) / float(kT)
            + np.asarray(payload["U_com_reduced"]),
            payload["target_reduced_energy"],
            "target_reduced_energy == U_target/kT + U_com_reduced",
        )
        require_aa_close(
            payload["logp"],
            payload["logq_ambient"],
            "logp == logq_ambient for exact 66D density",
        )
        require_aa_close(
            -np.asarray(payload["target_reduced_energy"])
            - np.asarray(payload["logq_ambient"]),
            payload["logw_raw"],
            "logw_raw == -target_reduced_energy - logq_ambient",
        )
    return metadata


def save_reweight_archive(path: str | Path, payload: Mapping[str, Any]) -> Path:
    validate_reweight_payload(payload)
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(path, **{key: np.asarray(value) for key, value in payload.items()})
    return path


def load_reweight_archive(
    path: str | Path,
    *,
    expected_density_mode: str | None = None,
    expected_metadata: Mapping[str, Any] | None = None,
) -> dict[str, np.ndarray]:
    with np.load(path, allow_pickle=False) as archive:
        payload = {key: archive[key] for key in archive.files}
    validate_reweight_payload(
        payload,
        expected_density_mode=expected_density_mode,
        expected_metadata=expected_metadata,
    )
    return payload
